### PR TITLE
Rebuttals: "Only for systems programming"

### PR DESCRIPTION
**Pull request by joshtriplett**
This would cover arguments that other languages are more suitable for
"high-level" programming.

### CODE REVIEW

**Comment by jonathandturner** [comment]
Seconded. This is a big one I hear a lot. "I don't know if I have a use for Rust" because our current image leans too heavily in the "Rust is a systems language for serious perf".

**Comment by joshtriplett** [comment]
Exactly.

A few possibilities for responses:

- A language doesn't have to have a single special-purpose niche. Just because Rust can go anywhere C can doesn't make it as low-level as C. It's a high-level language that provides access to low-level features.
- Huge library ecosystem for a wide variety of tasks. (Give examples!)
- You don't have to choose between performance, safety, and expressiveness; you can have them all. (Related to the slogan of "Rust: fast, reliable, productive—pick three.")

**Comment by jonathandturner** [comment]
Drilling into your second point even more, I think we could pick some examples of source code that read like "high level" languages like JavaScript and then put text with them that say these perform at the same speed as C.

Basically re-enforcing you can choose Rust because you like its expressiveness and just have perf as a nice side effect, if you want.

**Comment by joshtriplett** [comment]
@jonathandturner That sounds great. Show some things like iterators and show that they compile to the same code as a loop. Show an example of Rayon (`s/iter/par_iter/` and get performance). Show how you can easily integrate Rust with Python. Show a less-than-ten-lines example of getting data from a web API in JSON, processing it, and printing useful information.

**Comment by aturon** [comment]
I'm :+1: on this section, but will keep this PR open for now so we can work together to get some initial bullet points as well.

**Comment by Centril** [comment]
This is a frequent thing to say in #haskell (freenode) as well when Rust is mentioned; so I think it's a good section to include.

**Pull request merged**
